---
#ADD host OS vars for Master Config based on centos6/7
- name: Include distribution and version-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
      skip: true

- name: Install Packages
  ansible.builtin.package: 
    name: "{{ item }}"
    state: present
  with_items: 
    - "{{ nfs_packages }}"

- name: Setup service executable
  ansible.builtin.template:
    src: templates/nfs_watcher.sh.j2
    dest: "{{ service_executable }}"
    owner: root
    group: root
    mode: '0755'

- name: Template service file
  ansible.builtin.template:
    src: templates/{{ service_manager }}.j2
    dest: "{{ service_file_directory }}/{{ service_name }}{{ service_file_suffix }}"
    owner: root
    group: root
    mode: "{{ service_file_mode }}"
  when: install_watcher_service

#Enable but do not start the service, this should be provisioned in AMI's before NFS mounts are configured and we do not want to trigger any lifecycle actions
- name: Enable NFS watcher service
  ansible.builtin.service:
    name: "{{ service_name }}"
    enabled: yes
    state: stopped
  when: install_watcher_service

- name: Create roles directory if it does not exist
  ansible.builtin.file:
    path: "{{ mounts_role_dir }}/roles"
    state: directory
    mode: '0755'

- name: Copy NFS mount role to roles directory
  vars:
    ansible_python_interpreter: /usr/bin/python2.6  
  copy:
    src: nfs_mounts
    dest: "{{ mounts_role_dir }}/roles/nfs_mounts"
    mode: 0644
    directory_mode: 0755
