- name: Ensure pre-requisites are present
  package:
    name: "python"
    state: present

- name: Copy Script
  copy:
    src: files/cw_log_conf.py
    dest: "{{ (script_dir |length > 0) | ternary(script_dir, ansible_env.HOME) }}"
    mode: 0555

