- name: Ensure pre-requisites are present
  package:
    name: "python"
    state: present

- hosts: Copy Script
  tasks:
    - copy:
        src: files/cw_log_conf.py
        dest: "{{ script_dir if script_dir != '' else lookup('env', 'HOME') }}"

- name: Set rx file permissions
  file:
    path: "{{ script_dir if script_dir != '' else lookup('env', 'HOME') }}/cw_log_conf.py"
    state: present
    mode: 0555
