- name: Include distribution and version-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
      skip: true
      
- name: Ensure pre-requisites are present
  package:
    name: "{{ python_package_name }}"
    state: present

- name: Copy Script
  copy:
    src: files/cw_log_conf.py
    dest: "{{ (script_dir |length > 0) | ternary(script_dir, ansible_env.HOME) }}"
    mode: 0555

