- name: Ensure pre-requisites are present
  package:
    name: "python"
    state: present

- name: Copy Script
  copy:
    src: files/cw_log_conf.py
    dest: "{{ script_dir if script_dir != '' else ansible_env.HOME }}"
    mode: 0555

