---
packages:
  - audit
  - audit-libs
  - rsyslog

services: 
  - rsyslog
  - auditd

auditd_config_path: "/etc/audit/auditd.conf"
auditd_rules_path: "/etc/audit/rules.d/audit.rules"
audit_log_format: "RAW"

rsyslog_config_path: "/etc/audisp/plugins.d/syslog.conf"

grub_defaults_path: "/etc/default/grub"
grub_config_path: "/boot/grub/grub.conf"
grub_mkconfig_executable: "/usr/sbin/grub2-mkconfig"
