---
install_watcher_service: true
watcher_service_state: "stopped"
service_executable: "/usr/bin/nfs-watcher.sh"
service_name: "nfs-watcher"

mounts_role_dir: "/root"

nfs_watcher_wait_time: 15
nfs_watcher_list_timeout: 5

mounts_timeout: 0
mounts_parent_dir: "/mounts"
default_mount_options: [
  "rw",
  "hard",
  "nointr"
]

autofs_selinux_paths:
  - "{{ auto_mounts_file }}"
  - "{{ auto_master_file }}"
  - "{{ auto_master_file | dirname }}"