---
mounts_timeout: 0
mounts_parent_dir: "/mounts"
default_mount_options: [
  "rw",
  "hard",
  "nointr"
]
install_watcher_service: true

autofs_selinux_paths:
  - "{{ auto_mounts_file }}"
  - "{{ auto_master_file }}"
  - "{{ auto_master_file | dirname }}"