- name: Create /etc/clamd.d/scan.conf file for centos 6
  ansible.builtin.file:
    path: /etc/clamd.d/scan.conf
    state: touch

# Install Cronie for Freshclam
- name: Install cron (RedHat).
  package: name=cronie state=present

# Create socket file for ClamAV
- name: Create the socket file with correct ownership
  ansible.builtin.file:
    path: "{{ clamav_daemon_localsocket }}"
    state: touch
    owner: clam
    group: clam

# Setup Cron job for Freshclam to run every hour
- name: Freshclam cron.
  cron:
    name: 'Run freshclam'
    state: 'present'
    hour: '*/6'
    minute: '0'
    job: '/usr/bin/freshclam'
