---
- name: Define clamav_daemon
  ansible.builtin.set_fact:
    clamav_daemon: "{{ __clamav_daemon }}"
  when: clamav_daemon is not defined

- name: Define clamav_freshclam_daemon
  ansible.builtin.set_fact:
    clamav_freshclam_daemon: "{{ __clamav_freshclam_daemon }}"
  when:
    - clamav_freshclam_daemon is not defined
    - __clamav_freshclam_daemon is defined

- name: Define clamav_packages
  ansible.builtin.set_fact:
    clamav_packages: "{{ __clamav_packages | list }}"
  when: clamav_packages is not defined
