# Install Cronie for Freshclam
- name: Install cron (RedHat)
  ansible.builtin.package:
    name: cronie
    state: present

- name: Ensure Freshclam service is available
  ansible.builtin.template:
    src: clamd-freshclam.service.j2
    dest: /lib/systemd/system/clamd-freshclam.service
    mode: 0644
  register: freshclam_service_template

- name: Reload systemd after adding service
  ansible.builtin.systemd:
    state: stopped
    daemon_reload: true
    name: "{{ clamav_freshclam_daemon }}"
  when: freshclam_service_template.changed
  tags: ['skip_ansible_lint']
