---
molecule:
  ignore_paths:
    - lib
    - bin
    - library
dependency:
  name: galaxy
driver:
  name: docker
docker:
  containers:
    - name: centos6.9
      image: centos
      image_version: centos6.9
      privileged: True
      ansible_groups:
        - docker
verifier:
  name: goss
