---
- hosts: all
  pre_tasks:
    - name: install packages for testing under docker
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - selinux-policy
        - libselinux-python
        - openssh-server
        - which

  roles:
    - role: RHEL6-CIS
