---
clamav_ng_install_packages:
  - clamav1.4
  - clamav1.4-freshclam
  - clamd1.4

clamav_ng_clamav_exclude_paths:
  - /dev/
  - /proc/
  - /sys/
  - /run/
  - /etc/
  - /var/log/audit/
  - /var/lib/selinux/
