---
clamav_ng_install_packages:
  - clamav

clamav_ng_selinux_enabled: true

clamav_ng_log_group: clam
clamav_ng_run_group: clam

clamav_ng_clamav_config_file: /etc/clamd.conf
clamav_ng_clamav_service_name: clamd
clamav_ng_clamav_group: clam
clamav_ng_clamav_user: clam
clamav_ng_clamav_detectbrokenexecutables: true
clamav_ng_clamav_localsocketgroup: clam

clamav_ng_clamonacc_service: false
clamav_ng_clamonacc_distro_options:
  - "ScanOnAccess yes"

clamav_ng_freshclam_service: false
clamav_ng_freshclam_cron: true
clamav_ng_freshclam_group: clam
clamav_ng_freshclam_user: clam

clamav_ng_freshclam_privatemirror: clamav-mirror.sharedservices.aws.internal
