cwa_agent_ctl: "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl"
cwa_agent_config_file: "cloudwatch-config.json"
cw_agent_user: "cwagent"

force_flush_interval: 60
metrics_collection_interval: 60
cloudwatch_agent_log_file: "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"

region: "eu-west-2"

cw_collect_metrics: {
    "disk": {
      "measurement": [
        { "name": "total", "unit": "Gigabytes" },
        { "name": "used", "unit": "Gigabytes" },
        "used_percent"
      ],
      "metrics_collection_interval": 120,
      "resources": [
        "/",
        "/tmp"
      ]
    },
    "mem": {
      "measurement": [
          "total",
          "used_percent",
          "available_percent",
          "cached"
      ]
    },
    "swap": {
      "measurement": [
          "free",
          "used_percent"
      ]
    },
    "processes": {
      "measurement": [
        "sleeping",
        "dead"
      ]
    }
  }