---
- name: Converge
  hosts: all
  become: true

  vars:
      base_ami_dependencies:
        - openssl
        - openssh-server
      additional_packages:
        - php
      remove_packages: 
        - php
      additional_packages_pip:
        - name: awscli
          umask: "0022"
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Add CentOS 6 base repo
      template:
        src: CentOS-Base.repo.j2
        dest: /etc/yum.repos.d/CentOS-Base.repo
        mode: 0755
      register: centos_base_repo_template
      when: (ansible_os_family == 'RedHat') and (ansible_distribution_major_version | int == 6)

    - name: Set package name for older OSes.
      set_fact:
        pip_package: python-pip
      when: >
        (ansible_os_family == 'RedHat') and (ansible_distribution_major_version | int < 8)
        or (ansible_distribution == 'Debian') and (ansible_distribution_major_version | int < 10)
        or (ansible_distribution == 'Ubuntu') and (ansible_distribution_major_version | int < 18)

  roles:
    - role: os_package_control
