---
#ADD host OS vars for Master Config based on centos6/7
- name: Include distribution and version-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
      skip: true

- name: Setup Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items: 
    - "{{ mounts_parent_dir }}"

- name: Master Config
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    create: yes
    state: present
    owner: root
    group: root
    mode: 0644
    regexp: '^\{{ mounts_parent_dir }}.*'
    line: "{{ mounts_parent_dir}}  {{ auto_mounts_file }} --timeout {{ mounts_timeout }}"
  with_items:
   - "{{ auto_master_file }}"
  notify: 
    - Stop nfswatcher
    - Restart autofs
    - Start nfswatcher

- name: Master Config include
  ansible.builtin.lineinfile:
    path: "/etc/auto.master"
    create: no
    state: present
    owner: root
    group: root
    mode: 0644
    regexp: '{{ auto_master_file_include_regex }}'
    line: '{{ auto_master_file_include_line }}'
  notify: Restart autofs

- name: Template mounts
  ansible.builtin.template:
    src: templates/mounts.j2
    dest: "{{ auto_mounts_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: 
    - Stop nfswatcher
    - Restart autofs
    - Start nfswatcher

- name: Enable Autofs Service
  ansible.builtin.service:
    name: autofs
    state: started
    enabled: yes
  when: install_watcher_service
  notify: Start nfswatcher
