---
- name: restorecon
  ansible.builtin.command: restorecon -irv "{{ clamav_daemon_localsocket | dirname  }}"
  when: selinux_status == "Enforcing"

- name: restart clamav daemon
  ansible.builtin.service:
    name: "{{ clamav_daemon }}"
    state: restarted
  async: 30
  poll: 0
  when:
    - clamav_daemon_state != 'stopped'
    - ansible_virtualization_type != "docker"

- name: Reload systemd
  ansible.builtin.systemd:
    state: stopped
    daemon_reload: true
    name: "{{ clamav_freshclam_daemon }}"
