---
- name: restart clamav daemon
  service:
    name: "{{ clamav_daemon }}"
    state: restarted
  when: 
    - clamav_daemon_state != 'stopped' 
    - ansible_virtualization_type != "docker"

- name: Reload systemd
  systemd:
    state: stopped
    daemon_reload: true
    name: "{{ clamav_freshclam_daemon }}"