---

- name: Install downloaded package
  block:
    - name: Install SSM Agent from SSM URL
      ansible.builtin.apt:
        deb: "{{ ssm_url }}"
        state: present
  rescue:
    - name: Install alternative from SSM Agent URL
      ansible.builtin.apt:
        name: "{{ alt_url }}"
        state: present

- name: Enabled and/or Start SSM Agent service
  ansible.builtin.service:
    name: "{{ ssm_package_name }}"
    state: "{{ ssm_service_state }}"
    enabled: "{{ ssm_service_enabled }}"
