---
  - name: Include distribution and version-specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - files:
          - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
          - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
          - "{{ ansible_os_family }}.yml"
        skip: true

  - name: Include distribution and version-specific variables
    include_tasks: "{{ item }}"
    with_first_found:
      - files:
          - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
          - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
          - "{{ ansible_os_family }}.yml"
        skip: true