---
  - name: restorecon
    vars:
      ansible_python_interpreter: /usr/bin/python2
    ansible.builtin.command: restorecon -irv {{ item }}
    loop: "{{ autofs_selinux_paths }}"
    when: selinux_status == "Enforcing"

  - name: Stop nfswatcher
    service:
      name: nfs-watcher
      state: stopped
    when: install_watcher_service

  - name: Restart autofs
    service:
      name: autofs
      state: restarted

  - name: Start nfswatcher
    service:
      name: nfs-watcher
      state: started
    when: install_watcher_service

