---
  - name: Restart autofs
    service:
      name: nfs-watcher
      state: stopped
    notify: Restart autofs (2)

  - name: Restart autofs (2)
    service:
      name: autofs
      state: restarted

  - name: Restart nfswatcher
    service:
      name: nfs-watcher
      state: started
    when: install_watcher_service

