---
  - name: Stop nfswatcher
    service:
      name: nfs-watcher
      state: stopped
    when: install_watcher_service

  - name: Restart autofs
    service:
      name: autofs
      state: restarted

  - name: Start nfswatcher
    service:
      name: nfs-watcher
      state: started
    when: install_watcher_service

