galaxy_info:
  author: "Daniel Shepherd, Matt Shepherd, Bas Meijeri, amunter, daswars, Anton Opgenoort"
  description: "Ansible role to apply RHEL 6 CIS Baseline"
  company:
  license: MIT
  min_ansible_version: 2.2

  platforms:
  - name: EL
    versions:
      - 6

  galaxy_tags:
    - system
    - security
    - cis
    - hardening

dependencies: []
