---
# tasks file for compile_python_source
- name: Install required files to compile Python {{ version }}
  yum:
    name: "{{ dependencies_packages }}"
- name: Download Python {{ version }} from source
  get_url:
    url: "{{ python_version_url }}"
    dest: "{{ download_dest }}"
- name: Extract python {{ version }} archive
  ansible.builtin.unarchive:
    src: "{{ download_dest }}/{{ archive_filename }}"
    dest: "{{ download_dest }}/"
    remote_src: yes
- name: Run configure for Python
  command: chdir="{{ download_dest }}/{{ unarchive_filename }}" ./configure --enable-optimizations
- name: Make Python binary
  command: chdir="{{ download_dest }}/{{ unarchive_filename }}" make altinstall
- name: Download PIP install script
  get_url:
    url: "{{ pip_url }}"
    dest: "{{ download_dest }}/"
- name: Run PIP install script
  command: python"{{ major_version }}" "{{ download_dest }}/{{ pip_filename }}"