---
install_watcher_service: true
service_executable: "/usr/bin/nfs-watcher.sh"
service_name: "nfs-watcher"

mounts_role_dir: "/root"

nfs_watcher_wait_time: 15
nfs_watcher_list_timeout: 5

autofs_selinux_paths:
  - "{{ auto_mounts_file }}"
  - "{{ auto_master_file }}"
  - "{{ auto_master_file | dirname }}"