---
install_watcher_service: true
watcher_service_state: "stopped"
service_executable: "/usr/bin/nfs-watcher.sh"
service_name: "nfs-watcher"

mounts_role_dir: "/root"

nfs_watcher_wait_time: 15
nfs_watcher_list_timeout: 5
