Vagrant.configure("2") do |config|
  config.vm.define "centos7" do |centos7|
    centos7.vm.box = "centos/7"
    centos7.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
    end
  end

  config.vm.define "centos8" do |centos8|
    centos8.vm.box = "centos/8"
    centos8.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
    end
  end

  config.vm.define "centos6" do |centos6|
    centos6.vm.box = "geerlingguy/centos6"
    centos6.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
    end
  end

  config.vm.define "amzn2" do |amzn2|
    amzn2.vm.box = "gbailey/amzn2"
    amzn2.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
    end
  end
end
