- name: Reload CloudWatch Agent
  ansible.builtin.copy:
    src: "{{ working_dir }}{{ cwa_agent_config_file }}"
    dest: /tmp/cwa_agent_config_file
  notify: Reload CloudWatch Agent 2
  when: (ansible_virtualization_type != "docker") and (not ansible_check_mode)

- name: Reload CloudWatch Agent 2
  ansible.builtin.command:
    cmd: "{{ cwa_agent_ctl }} -a fetch-config -m ec2 -c file:/tmp/cwa_agent_config_file -s"
  when: ansible_virtualization_type != "docker"
