---
- name: Install | Install packages
  block:
    # Installing ClamAV on RHEL 9 usually includes an upgrade to the openssl and openssl-libs packages.
    # On early releases of RHEL 9, updating these packages in isolation causes sshd failures due to OpenSSL version mismatches.
    # The fix is to update the system to at least 9.2, something which this role will not do.
    - name: Install | Check minimum OS version
      ansible.builtin.debug:
        msg: "ERROR: At least RHEL 9.2 is required to avoid potential conflicts with ClamAV, OpenSSL and SSH"
      failed_when: true
      when: not (ansible_distribution_version|float >= '9.2'|float)

    - name: Install | Check if the RHUI repository file is disabled
      ansible.builtin.stat:
        path: /etc/yum.repos.d/redhat-rhui.repo.disabled
      register: repo_disabled

    - name: Install | Enable the RHUI repository file
      ansible.builtin.copy:
        src: /etc/yum.repos.d/redhat-rhui.repo.disabled
        dest: /etc/yum.repos.d/redhat-rhui.repo
        remote_src: yes
      when: repo_disabled.stat.exists

    - name: Install | Verify the RHUI repository file is present
      ansible.builtin.stat:
        path: /etc/yum.repos.d/redhat-rhui.repo
      register: repo_exists

    - name: Install | Enable CodeReady repo on RHEL9
      ansible.builtin.ini_file:
        dest: /etc/yum.repos.d/redhat-rhui.repo
        section: codeready-builder-for-rhel-9-rhui-rpms
        option: enabled
        value: 1
        no_extra_spaces: true
      when: repo_exists.stat.exists

    - name: Install | Check if EPEL is already installed
      ansible.builtin.stat:
        path: "{{ clamav_ng_rhel_epel_repo_file }}"
      register: epel_repo_file

    - name: Install | Import EPEL GPG key
      ansible.builtin.rpm_key:
        key: "{{ clamav_ng_rhel_epel_repo_gpg_key_url }}"
        state: present
      when: not epel_repo_file.stat.exists

    - name: Install | Install EPEL repository
      ansible.builtin.dnf:
        name: "{{ clamav_ng_rhel_epel_repo_url }}"
        state: present
      when: not epel_repo_file.stat.exists

    - name: Install | Enable the EPEL repository
      ansible.builtin.ini_file:
        path: "{{ clamav_ng_rhel_epel_repo_file }}"
        section: epel
        option: enabled
        value: 1
        no_extra_spaces: true

    - name: Install | Install packages via dnf
      ansible.builtin.dnf:
        name: "{{ clamav_ng_install_packages }}"
        state: present

- name: Install | Check for conflicting clamd-freshclam service
  block:
    - name: Install | Populate service facts
      ansible.builtin.service_facts:

    - name: Install | Stop and disable clamd-freshclam
      ansible.builtin.systemd:
        name: clamd-freshclam.service
        enabled: false
        masked: true
        state: stopped
        daemon_reexec: true
      when: ansible_facts['services']['clamd-freshclam.service']['status']|default('not-found') != 'not-found'
