---
- name: restart nrpe service
  service:
    name: "{{ nrpe_service }}"
    state: restarted

- name: enable-scripts
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
  loop: "{{ nagios_registration_services }}"