---
nagios_host: localhost
nrpe_allowed_hosts:
  - 127.0.0.1
nrpe_user: nrpe
nrpe_group: nrpe

nrpe_config: 
  nrpe_user: "{{ nrpe_user }}"
  nrpe_group: "{{ nrpe_group }}"
  nrpe_port: 5666
  nrpe_dont_blame_nrpe: 0
