---
# Set `auto_register_client` to true if you want to add service scripts to host so it can
# self-register with Nagios and de-register on shutdown.
# Registration scripts for manual registration will automatically be added: 
#   - /usr/local/bin/nagios-host-add 
#   - /usr/local/bin/nagios-host-remove
auto_register_client: false

# RHEL/CentOS > 6 only
auto_deregister_client: false

nagios_host: localhost
server_template_name: "linux-server"
nrpe_allowed_hosts:
  - 127.0.0.1
nrpe_user: nrpe
nrpe_group: nrpe

nrpe_config: 
  nrpe_user: "{{ nrpe_user }}"
  nrpe_group: "{{ nrpe_group }}"
  nrpe_port: 5666
  nrpe_dont_blame_nrpe: 0

nrpe_plugin_packages:
  - nagios-plugins
  - nagios-plugins-nrpe
  - nagios-plugins-load
  - nagios-plugins-procs
  - nagios-plugins-disk
  - nagios-plugins-users

nrpe_command:
  check_disk_all:
    script: check_disk
    option: -w 80 -c 90
  check_load:
    sudo: true
    script: check_load
    option: -w 15,10,5 -c 30,20,10
     
sudo_commands:
  - "{{ nrpe_plugins_dir }}/check_init_service"
  - "{{ nrpe_plugins_dir }}/check_service.sh"

